// GTNH manages dependencies through this file rather than build.gradle.
// Reference: https://github.com/GTNewHorizons/ExampleMod1.7.10/blob/master/dependencies.gradle

dependencies {
    // Tinkers' Construct (present in every GTNH instance)
    compileOnly('com.github.GTNewHorizons:TinkersConstruct:1.14.93-GTNH:dev')
    compileOnly('com.github.GTNewHorizons:Mantle:0.5.3:dev')
}
